--- # Sample configuration file for 1910calleditwantsitsphoneback
hardware:
  hardwarering: False
  dialermode: 'Astral'

soundfiles:
  startup: 'startup1.wav'
  shutdown: 'shutdown1.wav'
  ringtone: 'aselektriskbureau.wav'
  busy: 'uk24_busy.wav'
  error: 'uk24_unobtainable.wav'
  dialtone: 'uk24_dialtone.wav'
  ringing: 'uk24_ringing.wav'

sip:
  username: 'sip_username'
  password: 'sip_password'
  hostname: 'sip.example.com'
  port: 5060

alsadevices:
  ringer: 'plug:ringer'
  earpiece: 'plug:earpiece'
  mouthpiece: 'plug:mouthpiece'

diallingtimeout: 2
...
